/**
 * Centralized Error Codes
 *
 * Use these codes for consistent error handling across the application
 */
export const ErrorCodes = {
	// Authentication
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	UNAUTHORIZED: 'UNAUTHORIZED',
	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	INVALID_TOKEN: 'INVALID_TOKEN',
	TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
	AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
	EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
	EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
	ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
	ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
	ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
	ACCOUNT_ALREADY_VERIFIED: 'ACCOUNT_ALREADY_VERIFIED',

	// Authorization
	FORBIDDEN: 'FORBIDDEN',
	INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
	SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
	SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
	PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',

	// Validation
	BAD_REQUEST: 'BAD_REQUEST',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	INVALID_INPUT: 'INVALID_INPUT',
	MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
	INVALID_EMAIL: 'INVALID_EMAIL',
	INVALID_CPF: 'INVALID_CPF',
	INVALID_CNPJ: 'INVALID_CNPJ',
	INVALID_PHONE: 'INVALID_PHONE',
	WEAK_PASSWORD: 'WEAK_PASSWORD',

	// Resources
	NOT_FOUND: 'NOT_FOUND',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
	SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
	PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
	PENDING_PAYMENT_NOT_FOUND: 'PENDING_PAYMENT_NOT_FOUND',

	// Conflicts
	CONFLICT: 'CONFLICT',
	RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
	DUPLICATE_SUBSCRIPTION: 'DUPLICATE_SUBSCRIPTION',

	// Business Rules
	BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
	OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
	QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

	// Verification
	INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
	VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
	INVALID_PASSWORD_RESET_CODE: 'INVALID_PASSWORD_RESET_CODE',
	PASSWORD_RESET_CODE_EXPIRED: 'PASSWORD_RESET_CODE_EXPIRED',

	// Payment
	PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
	PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
	INVALID_PAYMENT_STATUS: 'INVALID_PAYMENT_STATUS',
	PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',

	// Rate Limiting
	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
	TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
	RESEND_LIMIT_EXCEEDED: 'RESEND_LIMIT_EXCEEDED',

	// External Services
	EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
	EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
	SMS_SEND_FAILED: 'SMS_SEND_FAILED',

	// Webhooks
	WEBHOOK_VALIDATION_ERROR: 'WEBHOOK_VALIDATION_ERROR',
	INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',

	// Server
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	DATABASE_ERROR: 'DATABASE_ERROR',
	CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
