export { AppError } from './app-error'
export { type ErrorCode, ErrorCodes } from './error-codes'
export {
	AccountAlreadyVerifiedError,
	AccountDeactivatedError,
	AccountLockedError,
	AccountNotVerifiedError,
	AuthenticationRequiredError,
	// 400 Bad Request
	BadRequestError,
	BusinessRuleError,
	ConfigurationError,
	// 409 Conflict
	ConflictError,
	DatabaseError,
	DuplicateSubscriptionError,
	EmailAlreadyExistsError,
	EmailNotVerifiedError,
	EmailSendFailedError,
	// 502 External
	ExternalServiceError,
	// 403 Forbidden
	ForbiddenError,
	InsufficientPermissionsError,
	// 500 Server
	InternalServerError,
	InvalidCNPJError,
	InvalidCPFError,
	InvalidCredentialsError,
	InvalidEmailError,
	InvalidInputError,
	InvalidPasswordResetCodeError,
	InvalidPaymentStatusError,
	InvalidPhoneError,
	InvalidTokenError,
	InvalidVerificationCodeError,
	InvalidWebhookSignatureError,
	MissingRequiredFieldError,
	// 404 Not Found
	NotFoundError,
	OperationNotAllowedError,
	PasswordResetCodeExpiredError,
	PaymentAlreadyProcessedError,
	PaymentExpiredError,
	PaymentGatewayError,
	PaymentNotFoundError,
	PendingPaymentNotFoundError,
	PlanLimitExceededError,
	PlanNotFoundError,
	QuotaExceededError,
	RateLimitExceededError,
	ResendLimitExceededError,
	ResourceAlreadyExistsError,
	SMSSendFailedError,
	SubscriptionExpiredError,
	SubscriptionNotFoundError,
	SubscriptionRequiredError,
	TokenExpiredError,
	TokenNotFoundError,
	TooManyAttemptsError,
	// 429 Rate Limit
	TooManyRequestsError,
	// 401 Unauthorized
	UnauthorizedError,
	UserNotFoundError,
	// 422 Validation
	ValidationError,
	VerificationCodeExpiredError,
	WeakPasswordError,
	WebhookValidationError,
} from './http-errors'
