export { AppError } from './app-error'
export { ErrorCodes, type ErrorCode } from './error-codes'
export {
	// 400 Bad Request
	BadRequestError,
	BusinessRuleError,
	AccountNotVerifiedError,
	AccountAlreadyVerifiedError,
	EmailNotVerifiedError,
	AccountLockedError,
	InvalidVerificationCodeError,
	VerificationCodeExpiredError,
	InvalidPasswordResetCodeError,
	PasswordResetCodeExpiredError,
	OperationNotAllowedError,
	QuotaExceededError,
	PaymentExpiredError,
	PaymentAlreadyProcessedError,
	InvalidPaymentStatusError,
	WebhookValidationError,
	// 401 Unauthorized
	UnauthorizedError,
	InvalidCredentialsError,
	TokenExpiredError,
	InvalidTokenError,
	TokenNotFoundError,
	AuthenticationRequiredError,
	InvalidWebhookSignatureError,
	// 403 Forbidden
	ForbiddenError,
	InsufficientPermissionsError,
	SubscriptionRequiredError,
	SubscriptionExpiredError,
	PlanLimitExceededError,
	AccountDeactivatedError,
	// 404 Not Found
	NotFoundError,
	UserNotFoundError,
	PlanNotFoundError,
	SubscriptionNotFoundError,
	PaymentNotFoundError,
	PendingPaymentNotFoundError,
	// 409 Conflict
	ConflictError,
	EmailAlreadyExistsError,
	ResourceAlreadyExistsError,
	DuplicateSubscriptionError,
	// 422 Validation
	ValidationError,
	InvalidInputError,
	MissingRequiredFieldError,
	InvalidEmailError,
	InvalidCPFError,
	InvalidCNPJError,
	InvalidPhoneError,
	WeakPasswordError,
	// 429 Rate Limit
	TooManyRequestsError,
	RateLimitExceededError,
	TooManyAttemptsError,
	ResendLimitExceededError,
	// 500 Server
	InternalServerError,
	DatabaseError,
	ConfigurationError,
	// 502 External
	ExternalServiceError,
	PaymentGatewayError,
	EmailSendFailedError,
	SMSSendFailedError,
} from './http-errors'
