import { t } from 'elysia'
import { brazilianStateSchema, maritalStatusSchema, nullableString } from '@/types/schemas'

export const createPropertyOwnerBodySchema = t.Object({
	name: t.String({ minLength: 2, maxLength: 200 }),
	documentType: t.Union([t.Literal('cpf'), t.Literal('cnpj')]),
	document: t.String({ minLength: 11, maxLength: 18 }),
	rg: t.Optional(t.String({ maxLength: 20 })),
	nationality: t.Optional(t.String({ maxLength: 100 })),
	maritalStatus: t.Optional(maritalStatusSchema),
	profession: t.Optional(t.String({ maxLength: 100 })),
	email: t.Optional(t.String({ format: 'email' })),
	phone: t.Optional(t.String({ minLength: 10, maxLength: 15 })),
	phoneSecondary: t.Optional(t.String({ minLength: 10, maxLength: 15 })),
	address: t.Optional(t.String({ maxLength: 500 })),
	addressNumber: t.Optional(t.String({ maxLength: 20 })),
	addressComplement: t.Optional(t.String({ maxLength: 100 })),
	neighborhood: t.Optional(t.String({ maxLength: 100 })),
	city: t.Optional(t.String({ maxLength: 100 })),
	state: t.Optional(brazilianStateSchema),
	zipCode: t.Optional(t.String({ minLength: 8, maxLength: 9 })),
	birthDate: t.Optional(t.String()),
	photoUrl: t.Optional(t.String()),
	notes: t.Optional(t.String({ maxLength: 2000 })),
})

export const createPropertyOwnerResponseSchema = t.Object({
	success: t.Boolean(),
	message: t.String(),
	data: t.Object({
		id: t.String(),
		companyId: t.String(),
		name: t.String(),
		documentType: t.String(),
		document: t.String(),
		rg: nullableString,
		nationality: nullableString,
		maritalStatus: nullableString,
		profession: nullableString,
		email: nullableString,
		phone: nullableString,
		phoneSecondary: nullableString,
		address: nullableString,
		addressNumber: nullableString,
		addressComplement: nullableString,
		neighborhood: nullableString,
		city: nullableString,
		state: nullableString,
		zipCode: nullableString,
		birthDate: nullableString,
		photoUrl: nullableString,
		notes: nullableString,
		createdAt: t.Date(),
	}),
})
