/**
 * Centralized Error Codes
 *
 * Use these codes for consistent error handling across the application
 */
export const ErrorCodes = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_CPF: "INVALID_CPF",
  INVALID_CNPJ: "INVALID_CNPJ",
  INVALID_PHONE: "INVALID_PHONE",
  WEAK_PASSWORD: "WEAK_PASSWORD",

  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  SMS_SEND_FAILED: "SMS_SEND_FAILED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
