import { t } from 'elysia'

export const propertyFeaturesSchema = t.Object({
	hasPool: t.Optional(t.Boolean()),
	hasGarden: t.Optional(t.Boolean()),
	hasGarage: t.Optional(t.Boolean()),
	hasElevator: t.Optional(t.Boolean()),
	hasGym: t.Optional(t.Boolean()),
	hasPlayground: t.Optional(t.Boolean()),
	hasSecurity: t.Optional(t.Boolean()),
	hasAirConditioning: t.Optional(t.Boolean()),
	hasFurnished: t.Optional(t.Boolean()),
	hasPetFriendly: t.Optional(t.Boolean()),
	hasBalcony: t.Optional(t.Boolean()),
	hasBarbecue: t.Optional(t.Boolean()),
})

export const updatePropertyParamsSchema = t.Object({
	id: t.String({ format: 'uuid' }),
})

export const updatePropertyBodySchema = t.Object({
	ownerId: t.Optional(t.String({ format: 'uuid' })),
	brokerId: t.Optional(t.Union([t.String({ format: 'uuid' }), t.Null()])),
	title: t.Optional(t.String({ minLength: 3, maxLength: 200 })),
	description: t.Optional(t.Union([t.String({ maxLength: 5000 }), t.Null()])),
	type: t.Optional(
		t.Union([
			t.Literal('house'),
			t.Literal('apartment'),
			t.Literal('land'),
			t.Literal('commercial'),
			t.Literal('rural'),
		]),
	),
	listingType: t.Optional(t.Union([t.Literal('rent'), t.Literal('sale'), t.Literal('both')])),
	status: t.Optional(
		t.Union([
			t.Literal('available'),
			t.Literal('rented'),
			t.Literal('sold'),
			t.Literal('maintenance'),
			t.Literal('unavailable'),
		]),
	),
	address: t.Optional(t.Union([t.String({ maxLength: 500 }), t.Null()])),
	addressNumber: t.Optional(t.Union([t.String({ maxLength: 20 }), t.Null()])),
	addressComplement: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	neighborhood: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	city: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	state: t.Optional(t.Union([t.String({ minLength: 2, maxLength: 2 }), t.Null()])),
	zipCode: t.Optional(t.Union([t.String({ minLength: 8, maxLength: 9 }), t.Null()])),
	bedrooms: t.Optional(t.Number({ minimum: 0 })),
	bathrooms: t.Optional(t.Number({ minimum: 0 })),
	suites: t.Optional(t.Number({ minimum: 0 })),
	parkingSpaces: t.Optional(t.Number({ minimum: 0 })),
	area: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	totalArea: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	builtArea: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	floor: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	totalFloors: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	yearBuilt: t.Optional(t.Union([t.Number({ minimum: 1800, maximum: 2100 }), t.Null()])),
	rentalPrice: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	salePrice: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	iptuPrice: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	condoFee: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	commissionPercentage: t.Optional(t.Union([t.Number({ minimum: 0, maximum: 10000 }), t.Null()])),
	commissionValue: t.Optional(t.Union([t.Number({ minimum: 0 }), t.Null()])),
	isMarketplace: t.Optional(t.Boolean()),
	notes: t.Optional(t.Union([t.String({ maxLength: 2000 }), t.Null()])),
	features: t.Optional(propertyFeaturesSchema),
})

export const updatePropertyResponseSchema = t.Object({
	success: t.Boolean(),
	message: t.String(),
	data: t.Object({
		id: t.String(),
		code: t.Union([t.String(), t.Null()]),
		companyId: t.String(),
		ownerId: t.String(),
		brokerId: t.Union([t.String(), t.Null()]),
		title: t.String(),
		description: t.Union([t.String(), t.Null()]),
		type: t.String(),
		listingType: t.String(),
		status: t.String(),
		address: t.Union([t.String(), t.Null()]),
		addressNumber: t.Union([t.String(), t.Null()]),
		addressComplement: t.Union([t.String(), t.Null()]),
		neighborhood: t.Union([t.String(), t.Null()]),
		city: t.Union([t.String(), t.Null()]),
		state: t.Union([t.String(), t.Null()]),
		zipCode: t.Union([t.String(), t.Null()]),
		bedrooms: t.Union([t.Number(), t.Null()]),
		bathrooms: t.Union([t.Number(), t.Null()]),
		suites: t.Union([t.Number(), t.Null()]),
		parkingSpaces: t.Union([t.Number(), t.Null()]),
		area: t.Union([t.Number(), t.Null()]),
		totalArea: t.Union([t.Number(), t.Null()]),
		builtArea: t.Union([t.Number(), t.Null()]),
		floor: t.Union([t.Number(), t.Null()]),
		totalFloors: t.Union([t.Number(), t.Null()]),
		yearBuilt: t.Union([t.Number(), t.Null()]),
		rentalPrice: t.Union([t.Number(), t.Null()]),
		salePrice: t.Union([t.Number(), t.Null()]),
		iptuPrice: t.Union([t.Number(), t.Null()]),
		condoFee: t.Union([t.Number(), t.Null()]),
		commissionPercentage: t.Union([t.Number(), t.Null()]),
		commissionValue: t.Union([t.Number(), t.Null()]),
		isMarketplace: t.Boolean(),
		notes: t.Union([t.String(), t.Null()]),
		features: t.Union([propertyFeaturesSchema, t.Null()]),
		createdBy: t.String(),
		createdAt: t.Date(),
		updatedAt: t.Date(),
	}),
})
