import { t } from 'elysia'

const brazilianStateSchema = t.Union([
	t.Literal('AC'),
	t.Literal('AL'),
	t.Literal('AP'),
	t.Literal('AM'),
	t.Literal('BA'),
	t.Literal('CE'),
	t.Literal('DF'),
	t.Literal('ES'),
	t.Literal('GO'),
	t.Literal('MA'),
	t.Literal('MT'),
	t.Literal('MS'),
	t.Literal('MG'),
	t.Literal('PA'),
	t.Literal('PB'),
	t.Literal('PR'),
	t.Literal('PE'),
	t.Literal('PI'),
	t.Literal('RJ'),
	t.Literal('RN'),
	t.Literal('RS'),
	t.Literal('RO'),
	t.Literal('RR'),
	t.Literal('SC'),
	t.Literal('SP'),
	t.Literal('SE'),
	t.Literal('TO'),
])

export const updatePropertyOwnerParamsSchema = t.Object({
	id: t.String({ format: 'uuid' }),
})

export const updatePropertyOwnerBodySchema = t.Object({
	name: t.Optional(t.String({ minLength: 2, maxLength: 200 })),
	documentType: t.Optional(t.Union([t.Literal('cpf'), t.Literal('cnpj')])),
	document: t.Optional(t.String({ minLength: 11, maxLength: 18 })),
	rg: t.Optional(t.Union([t.String({ maxLength: 20 }), t.Null()])),
	nationality: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	maritalStatus: t.Optional(
		t.Union([
			t.Literal('solteiro'),
			t.Literal('casado'),
			t.Literal('divorciado'),
			t.Literal('viuvo'),
			t.Literal('uniao_estavel'),
			t.Null(),
		]),
	),
	profession: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	email: t.Optional(t.Union([t.String({ format: 'email' }), t.Null()])),
	phone: t.Optional(t.Union([t.String({ minLength: 10, maxLength: 15 }), t.Null()])),
	phoneSecondary: t.Optional(t.Union([t.String({ minLength: 10, maxLength: 15 }), t.Null()])),
	address: t.Optional(t.Union([t.String({ maxLength: 500 }), t.Null()])),
	addressNumber: t.Optional(t.Union([t.String({ maxLength: 20 }), t.Null()])),
	addressComplement: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	neighborhood: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	city: t.Optional(t.Union([t.String({ maxLength: 100 }), t.Null()])),
	state: t.Optional(t.Union([brazilianStateSchema, t.Null()])),
	zipCode: t.Optional(t.Union([t.String({ minLength: 8, maxLength: 9 }), t.Null()])),
	birthDate: t.Optional(t.Union([t.String(), t.Null()])),
	photoUrl: t.Optional(t.Union([t.String(), t.Null()])),
	notes: t.Optional(t.Union([t.String({ maxLength: 2000 }), t.Null()])),
})

export const updatePropertyOwnerResponseSchema = t.Object({
	success: t.Boolean(),
	message: t.String(),
	data: t.Object({
		id: t.String(),
		companyId: t.String(),
		name: t.String(),
		documentType: t.String(),
		document: t.String(),
		rg: t.Union([t.String(), t.Null()]),
		nationality: t.Union([t.String(), t.Null()]),
		maritalStatus: t.Union([t.String(), t.Null()]),
		profession: t.Union([t.String(), t.Null()]),
		email: t.Union([t.String(), t.Null()]),
		phone: t.Union([t.String(), t.Null()]),
		phoneSecondary: t.Union([t.String(), t.Null()]),
		address: t.Union([t.String(), t.Null()]),
		addressNumber: t.Union([t.String(), t.Null()]),
		addressComplement: t.Union([t.String(), t.Null()]),
		neighborhood: t.Union([t.String(), t.Null()]),
		city: t.Union([t.String(), t.Null()]),
		state: t.Union([t.String(), t.Null()]),
		zipCode: t.Union([t.String(), t.Null()]),
		birthDate: t.Union([t.String(), t.Null()]),
		photoUrl: t.Union([t.String(), t.Null()]),
		notes: t.Union([t.String(), t.Null()]),
		createdBy: t.String(),
		createdAt: t.Date(),
		updatedAt: t.Date(),
	}),
})
