export const AUTH_CONSTANTS = {
	EMAIL_VERIFICATION: {
		MAX_RESEND_ATTEMPTS: 5,
		MAX_CODE_ATTEMPTS: 5,
		INITIAL_COOLDOWN_SECONDS: 30,
		SUBSEQUENT_COOLDOWN_SECONDS: 60,
		THROTTLE_DELAYS: [0, 0, 5, 10, 15],
	},

	PASSWORD_RESET: {
		MAX_RESEND_ATTEMPTS: 5,
		MAX_CODE_ATTEMPTS: 5,
		COOLDOWN_SECONDS: 60,
		BLOCK_DURATION_MINUTES: 30,
		THROTTLE_DELAYS: [0, 0, 5, 15, 30],
	},

	LOGIN: {
		MAX_ATTEMPTS: 5,
		BLOCK_DURATION_MINUTES: 15,
	},
} as const
