process.env.NODE_ENV = 'test'
process.env.PORT = '3001'
process.env.CORS_ORIGIN = 'http://localhost:5173'
process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/gradely_test'
process.env.JWT_ACCESS_SECRET = 'test-access-secret-minimum-32-characters-long'
process.env.JWT_ACCESS_EXPIRES_IN = '15m'
process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-minimum-32-characters-long'
process.env.JWT_REFRESH_EXPIRES_IN = '7d'
