import { t } from "elysia";

export const propertyFeaturesSchema = t.Object({
  hasPool: t.Optional(t.Boolean()),
  hasGarden: t.Optional(t.Boolean()),
  hasGarage: t.Optional(t.Boolean()),
  hasElevator: t.Optional(t.Boolean()),
  hasGym: t.Optional(t.Boolean()),
  hasPlayground: t.Optional(t.Boolean()),
  hasSecurity: t.Optional(t.Boolean()),
  hasAirConditioning: t.Optional(t.Boolean()),
  hasFurnished: t.Optional(t.Boolean()),
  hasPetFriendly: t.Optional(t.Boolean()),
  hasBalcony: t.Optional(t.Boolean()),
  hasBarbecue: t.Optional(t.Boolean()),
});

export const createPropertyBodySchema = t.Object({
  ownerId: t.String({ format: "uuid" }),
  brokerId: t.Optional(t.String({ format: "uuid" })),
  title: t.String({ minLength: 3, maxLength: 200 }),
  description: t.Optional(t.String({ maxLength: 5000 })),
  type: t.Union([
    t.Literal("house"),
    t.Literal("apartment"),
    t.Literal("land"),
    t.Literal("commercial"),
    t.Literal("rural"),
  ]),
  listingType: t.Union([t.Literal("rent"), t.Literal("sale"), t.Literal("both")]),
  address: t.String({ maxLength: 500 }),
  neighborhood: t.Optional(t.String({ maxLength: 100 })),
  city: t.String({ maxLength: 100 }),
  state: t.String({ minLength: 2, maxLength: 2 }),
  zipCode: t.Optional(t.String({ minLength: 8, maxLength: 9 })),
  bedrooms: t.Optional(t.Number({ minimum: 0 })),
  bathrooms: t.Optional(t.Number({ minimum: 0 })),
  parkingSpaces: t.Optional(t.Number({ minimum: 0 })),
  area: t.Optional(t.Number({ minimum: 0 })),
  rentalPrice: t.Optional(t.Number({ minimum: 0 })),
  salePrice: t.Optional(t.Number({ minimum: 0 })),
  iptuPrice: t.Optional(t.Number({ minimum: 0 })),
  condoFee: t.Optional(t.Number({ minimum: 0 })),
  features: t.Optional(propertyFeaturesSchema),
});

export const createPropertyResponseSchema = t.Object({
  success: t.Boolean(),
  message: t.String(),
  data: t.Object({
    id: t.String(),
    companyId: t.String(),
    ownerId: t.String(),
    brokerId: t.Union([t.String(), t.Null()]),
    title: t.String(),
    description: t.Union([t.String(), t.Null()]),
    type: t.String(),
    listingType: t.String(),
    status: t.String(),
    address: t.Union([t.String(), t.Null()]),
    neighborhood: t.Union([t.String(), t.Null()]),
    city: t.Union([t.String(), t.Null()]),
    state: t.Union([t.String(), t.Null()]),
    zipCode: t.Union([t.String(), t.Null()]),
    bedrooms: t.Union([t.Number(), t.Null()]),
    bathrooms: t.Union([t.Number(), t.Null()]),
    parkingSpaces: t.Union([t.Number(), t.Null()]),
    area: t.Union([t.Number(), t.Null()]),
    rentalPrice: t.Union([t.Number(), t.Null()]),
    salePrice: t.Union([t.Number(), t.Null()]),
    iptuPrice: t.Union([t.Number(), t.Null()]),
    condoFee: t.Union([t.Number(), t.Null()]),
    features: t.Union([t.Record(t.String(), t.Any()), t.Null()]),
    createdAt: t.Date(),
  }),
});
