import { t } from 'elysia'

export const propertyFeaturesSchema = t.Object({
	hasPool: t.Optional(t.Boolean()),
	hasGarden: t.Optional(t.Boolean()),
	hasGarage: t.Optional(t.Boolean()),
	hasElevator: t.Optional(t.Boolean()),
	hasGym: t.Optional(t.Boolean()),
	hasPlayground: t.Optional(t.Boolean()),
	hasSecurity: t.Optional(t.Boolean()),
	hasAirConditioning: t.Optional(t.Boolean()),
	hasFurnished: t.Optional(t.Boolean()),
	hasPetFriendly: t.Optional(t.Boolean()),
	hasBalcony: t.Optional(t.Boolean()),
	hasBarbecue: t.Optional(t.Boolean()),
})

export const createPropertyBodySchema = t.Object({
	ownerId: t.String({ format: 'uuid' }),
	brokerId: t.Optional(t.String({ format: 'uuid' })),
	title: t.String({ minLength: 3, maxLength: 200 }),
	description: t.Optional(t.String({ maxLength: 5000 })),
	type: t.Union([
		t.Literal('house'),
		t.Literal('apartment'),
		t.Literal('land'),
		t.Literal('commercial'),
		t.Literal('rural'),
	]),
	listingType: t.Union([t.Literal('rent'), t.Literal('sale'), t.Literal('both')]),
	address: t.String({ maxLength: 500 }),
	addressNumber: t.Optional(t.String({ maxLength: 20 })),
	addressComplement: t.Optional(t.String({ maxLength: 100 })),
	neighborhood: t.Optional(t.String({ maxLength: 100 })),
	city: t.String({ maxLength: 100 }),
	state: t.String({ minLength: 2, maxLength: 2 }),
	zipCode: t.Optional(t.String({ minLength: 8, maxLength: 9 })),
	bedrooms: t.Optional(t.Number({ minimum: 0 })),
	bathrooms: t.Optional(t.Number({ minimum: 0 })),
	suites: t.Optional(t.Number({ minimum: 0 })),
	parkingSpaces: t.Optional(t.Number({ minimum: 0 })),
	area: t.Optional(t.Number({ minimum: 0 })),
	totalArea: t.Optional(t.Number({ minimum: 0 })),
	builtArea: t.Optional(t.Number({ minimum: 0 })),
	floor: t.Optional(t.Number({ minimum: 0 })),
	totalFloors: t.Optional(t.Number({ minimum: 0 })),
	yearBuilt: t.Optional(t.Number({ minimum: 1800, maximum: 2100 })),
	rentalPrice: t.Optional(t.Number({ minimum: 0 })),
	salePrice: t.Optional(t.Number({ minimum: 0 })),
	iptuPrice: t.Optional(t.Number({ minimum: 0 })),
	condoFee: t.Optional(t.Number({ minimum: 0 })),
	commissionPercentage: t.Optional(t.Number({ minimum: 0, maximum: 10000 })), // 0-100% em centesimos
	commissionValue: t.Optional(t.Number({ minimum: 0 })),
	isMarketplace: t.Optional(t.Boolean()),
	notes: t.Optional(t.String({ maxLength: 2000 })),
	features: t.Optional(propertyFeaturesSchema),
})

export const createPropertyResponseSchema = t.Object({
	success: t.Boolean(),
	message: t.String(),
	data: t.Object({
		id: t.String(),
		code: t.Union([t.String(), t.Null()]),
		companyId: t.String(),
		ownerId: t.String(),
		brokerId: t.Union([t.String(), t.Null()]),
		title: t.String(),
		description: t.Union([t.String(), t.Null()]),
		type: t.String(),
		listingType: t.String(),
		status: t.String(),
		address: t.Union([t.String(), t.Null()]),
		addressNumber: t.Union([t.String(), t.Null()]),
		addressComplement: t.Union([t.String(), t.Null()]),
		neighborhood: t.Union([t.String(), t.Null()]),
		city: t.Union([t.String(), t.Null()]),
		state: t.Union([t.String(), t.Null()]),
		zipCode: t.Union([t.String(), t.Null()]),
		bedrooms: t.Union([t.Number(), t.Null()]),
		bathrooms: t.Union([t.Number(), t.Null()]),
		suites: t.Union([t.Number(), t.Null()]),
		parkingSpaces: t.Union([t.Number(), t.Null()]),
		area: t.Union([t.Number(), t.Null()]),
		totalArea: t.Union([t.Number(), t.Null()]),
		builtArea: t.Union([t.Number(), t.Null()]),
		floor: t.Union([t.Number(), t.Null()]),
		totalFloors: t.Union([t.Number(), t.Null()]),
		yearBuilt: t.Union([t.Number(), t.Null()]),
		rentalPrice: t.Union([t.Number(), t.Null()]),
		salePrice: t.Union([t.Number(), t.Null()]),
		iptuPrice: t.Union([t.Number(), t.Null()]),
		condoFee: t.Union([t.Number(), t.Null()]),
		commissionPercentage: t.Union([t.Number(), t.Null()]),
		commissionValue: t.Union([t.Number(), t.Null()]),
		isMarketplace: t.Boolean(),
		notes: t.Union([t.String(), t.Null()]),
		features: t.Union([t.Record(t.String(), t.Any()), t.Null()]),
		createdAt: t.Date(),
	}),
})
